### ISSUE TITLE
Test TCPSpout ( Syphon for Windows)

### ISSUE THREAD

**Issue by radames** [fact-liverpool/Be-Famous-IRL#1]
We need to access the Windows machine connected to the big Led display and test if this app work receiving Syphon screen from our OSXs machines in the network
http://techlife.sg/TCPSpout/
http://spout.zeal.co/

**Comment by muff7** [comment]
When you're on the main lan i.e.. FACTHQ or Exhibitions you can VNC to the windows machine on the IP 192.168.0.200 I'll email you both the login details now.

**Comment by thiagohersan** [comment]
yoho ! jackpot ! we h4ck3rs !

**Comment by thiagohersan** [comment]
thank you !

**Comment by muff7** [comment]
L337 s|<1llz, s|<1llz, s|<1llz!

**Comment by radames** [comment]
Hey @muff7 trying to connect to the computer and I'm getting this

<img width="489" alt="screen shot 2016-01-16 at 17 22 19" src="https://cloud.githubusercontent.com/assets/102277/12373590/03514574-bc76-11e5-9746-43999bada1d9.png">

Is there any other way to access the computer?

**Comment by radames** [comment]
solve using the microsoft remote desktop, although the tests with the spout were unsuccessful due the the poor computer performance, low memory.
