### ISSUE TITLE
AC Power in the Square?

### ISSUE THREAD

**Issue by radames** [fact-liverpool/Be-Famous-IRL#2]
We're wondering how easy is to access AC in the square outside FACT? @thiagohersan

**Comment by muff7** [comment]
No power on the square. 

We have 750w generator we use, the cafe Central Perk have given us power in the past also if you need more wattage!

**Comment by radames** [comment]
We don't need that much power, but the generator seems a pretty good solution. Does it use a battery as well? Can we charge it and use for a couple of hours?

**Comment by thiagohersan** [comment]
Generator FTW !
