### ISSUE TITLE
WiFi signal strength in the Square

### ISSUE THREAD

**Issue by radames** [fact-liverpool/Be-Famous-IRL#4]
Do we need special wifi antenna to access FACT network in the square?

**Comment by muff7** [comment]
We have a https://www.ubnt.com/unifi/unifi-ap-ac/ in the connects space. Has a range of 122m. We've moved this nearer to the window in the past to allow wifi access on the square. 

Might just be worth checking the current signal strength, how much data do you need to send each snap?

**Comment by thiagohersan** [comment]
dope ! 50x50 pixels ... through syphon.
we should test all of this next week... if you have some time.

**Comment by radames** [comment]
Just talked to Andrew Joy and he added the FACTHQ wifi to the external access point in the FACT connect space therefore we will be able to connect from anywhere in the square to the windows LED machine
