### ISSUE TITLE
Grab the app screen and send to the pixels?

### ISSUE THREAD

**Issue by radames** [fact-liverpool/Be-Famous-IRL#7]
We finish the app to send the pixels to the windows machine through the network #5.
Question, does the application in the windows machine should be running in fullscreen? Or you can grab any screen area with the LEDs panel software?

Now the viewer is as 500x500 window. A stretched version of the original 50x50 image.

**Comment by muff7** [comment]
I've told you this AFK but!

We can select any area of the screen. It's a bit fiddily, you have to choose the area by percentage instead of pixels but it's doable.

**Comment by thiagohersan** [comment]
I've seen the future and it looks marvelous.

**Comment by muff7** [comment]
Here's the screengrabs from the mini tutorial. 
![Choosing a Cue/Select Wizard](https://cloud.githubusercontent.com/assets/6765297/12556658/f748f2ee-c37e-11e5-8d0f-d3df489e20ac.png)
![Video Wizzard]()
![Choosing the sCreen capture/Cliiping area](https://cloud.githubusercontent.com/assets/6765297/12556680/11e5ddf6-c37f-11e5-8de4-98deeba79d39.png)
![Preview Window](https://cloud.githubusercontent.com/assets/6765297/12556683/16a27264-c37f-11e5-88ca-ad79ccedee68.png)

**Comment by radames** [comment]
that's beautiful! going to share my face right now...

**Comment by radames** [comment]
Done, the window must full screen then we can adjust the clipping offset 
![img_20160125_190924](https://cloud.githubusercontent.com/assets/102277/12563973/a8f14724-c3a4-11e5-8a6b-65c041a7a16a.jpg)
